# Generated by Django 3.2.4 on 2021-07-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prise',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
